<?php
use Drupal\graphql_api\Schema;
use GraphQL\GraphQL;

/**
 * @file
 */
define('GRAPHQL_API_PATH', drupal_get_path('module', 'graphql_api'));

/**
 * Implements hook_menu().
 *
 * @return array
 */
function graphql_api_menu() {
  $items = [];

  $items['graphql'] = [
    'page callback' => 'graphql_api_page_callback',
    'page arguments' => [],
    'access arguments' => ['use graphql_api query'],
    'access callback' => 'graphql_api_access_callback',
    'file path' => GRAPHQL_API_PATH . '/includes',
    'file' => 'graphql_api_page_callback.inc'
  ];

  $items['graphqleditor'] = [
    'title' => 'GraphiQL',
    'page callback' => 'graphql_api_graphqleditor_callback',
    'page arguments' => [],
    'access arguments' => ['use graphql_api query'],
    'file path' => GRAPHQL_API_PATH . '/includes',
    'file' => 'graphql_api_graphqleditor_callback.inc'
  ];

  return $items;
}

function graphql_api_access_callback($perm) {
  if (!empty($_SERVER['HTTP_GRAPHQL_TOKEN']) && $_SERVER['HTTP_GRAPHQL_TOKEN'] === variable_get('graphql_token', 'graphql_private_token')) {
    return TRUE;
  }
  return user_access($perm);
}

/**
 * Implements hook_permission().
 */
function graphql_api_permission() {
  return array(
    'use graphql_api query' => array(
      'title' => t('Use GraphQL query'),
      'description' => t('Perform query on graphql endpoint.'),
    ),
  );
}

/**
 * Get GraphQL info
 *
 * @return array|mixed
 */
function graphql_api_info() {
  foreach (module_list() as $module => $module_info) {
    module_load_include('inc', $module, $module.'.graphql');
  }
  $info = module_invoke_all('graphql_api_info');
  drupal_alter('graphql_api_info', $info);
  return $info;
}

/**
 * Get entity field query
 *
 * @param $entity_type
 * @param array $conditions
 * @return bool|\EntityFieldQuery
 */
function graphql_api_entity_get_query($entity_type, $conditions = []) {
  $info = entity_get_info($entity_type);
  $props = entity_get_property_info($entity_type);
  if (!$info || !$props) {
    return FALSE;
  }

  $all_fields = [];

  // get all fields attached to this entity type
  if (!empty($props['bundles'])) {
    foreach ($props['bundles'] as $bundle => $bundle_info) {
      foreach ($bundle_info['properties'] as $field => $field_info) {
        $all_fields[] = $field;
      }
    }
  }

  $query = new EntityFieldQuery();

  $deleted_key = isset($info['entity keys']['deleted']) ? $info['entity keys']['deleted'] : null;
  if ($deleted_key && !isset($conditions[$deleted_key])) {
    $query->propertyCondition($deleted_key, 0);
  }

  $query->entityCondition('entity_type', $entity_type);
  foreach ($conditions as $prop => $val) {
    if (in_array($prop, $info['schema_fields_sql']['base table'])) {
      $query->propertyCondition($prop, $val);
    }
    else if (in_array($prop, $all_fields)) {
      foreach ($val as $col => $f_val) {
        $query->fieldCondition($prop, $col, $f_val);
      }
    }
  }

  return $query;
}

/**
 * Execute query in file
 */
function graphql_api_query_file($file, $args = []) {
  $query_task = file_get_contents($file);
  $shema = new Schema();
  $schema_build = $shema->build();
  $data = GraphQL::execute(
    $schema_build,
    $query_task,
    null,
    null,
    $args
  );
  return $data;
}

/**
 * Symfony VarDumper fallback
 */
if (!function_exists('dump')) {
  function dump() {
    return call_user_func_array('var_dump', func_get_args());
  }
}